### ISSUE TITLE
Question: Target program counter sampling

### ISSUE THREAD

**Issue by AloyseTech** [adafruit/Adafruit_DAP#2]
Hello,

This is more a question than an issue.

Would it be possible to use this library to only sample the target program counter over SWD and nothing else?

Thanks in advance for your reply :)

**Comment by deanm1278** [comment]
Hey I believe the functionality may be in there somewhere but I'm not sure how to do it right now. Note that in order to to read the program counter you will have to continuously halt your target, read the PC, and then resume your target.
Do you need to do this with a microcontroller? You could probably use OpenOCD with a CMSIS-DAP debugger connected to a PC to do this using the Profile command (see the bottom of this page http://openocd.org/doc/html/General-Commands.html)

Please use the forums for things that are not code issues :)
